### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by TroyWilson1**
Personal Hash Tracker (PHT) Just a small app that stores IPFS Hashes with a description that you can search. Everything is stored in a JSON file.

### CODE REVIEW

**Comment by koalalorenzo** [comment]
I think that your code needs a little more of refactoring :) It works only on your Mac, and only if you have the right username (`troywilson`).

**Comment by TroyWilson1** [comment]
What refactoring do you mean? The only change is each user needs to set where they want their hash list stored.

Have a great day!

Troy Wilson
Phone: 913-667-9662
Fax: 1-877-748-9636
Email: Troy@MerchantGuy.com

PGP Encryption Available upon request.
Fingerprint: 6D00 3C6B 74F8 D97A CC05 4AEE 6E2F 137E 5F0D BD

**Comment by TroyWilson1** [comment]
I would love to change this to fit the needs of all. The only line is where to store the hash list. Line 39 of the code. How should I change this so it passes?

"/Users/troywilson/testing/pht/hash.json"

**Comment by Stebalien** [comment]
@TroyWilson1 you can, for example, default to storing the list in `~/.pht.json` and make this configurable (e.g., through an environment variable).

---

Not really necessary but, if you're interested in alternative designs, you might consider using MFS (the `ipfs files` commands). If you did that, you'd be able to store all this information within IPFS itself.

**Comment by TroyWilson1** [comment]
I can figure out the ~/.pht.json with an environment variable. I have looked into storing it in IPFS as well but, I have been unable to master mutability with IPNS since the link is invalid after 24h without trying to constantly republish to keep the link valid.

**Comment by Stebalien** [comment]
> I have been unable to master mutability with IPNS since the link is invalid after 24h without trying to constantly republish to keep the link valid.

That should happen automatically in the background but yes, the node must remain online.

However, that shouldn't affect storing files in MFS. Use the `ipfs files` commands, you shouldn't need to mess with IPNS.

**Comment by TroyWilson1** [comment]
I will need to use IPNS because the hash file is added to and deleted from so to store this primary file in IPFS will require IPNS since the file changes.

**Comment by Stebalien** [comment]
> I will need to use IPNS because the hash file is added to and deleted from so to store this primary file in IPFS will require IPNS since the file changes.

You only need IPNS to get mutable names in a global namespace. MFS (`ipfs files`) provides a *local* namespace. You can add/remove files to/from your local namespace without ever exposing these changes with MFS.

Note: these files will still *exist* within IPFS so beware the privacy implications.

**Comment by TroyWilson1** [comment]
Today I’m going to learn how ipfs files works since all I get is Error: file does not exist anytime I try the commands out or to add anything to it.

**Comment by TroyWilson1** [comment]
OK, I spent some time today learning ipfs files which basically replaced the need for this script. Now I just need to figure out how to use ipfs files in python scripts to call files.

**Comment by Stebalien** [comment]
Take a look at https://github.com/ipfs/py-ipfs-api

**Pull request closed without merging**
