### PR TITLE
fix: Remove entries with broken links

### PR DESCRIPTION
**Pull request by SgtPooki**
See https://app.circleci.com/pipelines/github/ipfs/awesome-ipfs/1155/workflows/3a0e7492-db09-4859-8219-d4ac50df169e/jobs/1858

## What kind of PR is this?
**Select only one** *to speed up review/approval; i.e., don't lump an addition and a removal into a single PR.*

- [N/A] **Adding** something new to awesome-ipfs
- [N/A] **Editing** something already listed on awesome-ipfs
- [x] **Removing** something from awesome-ipfs
- [N/A] **Something else** *(if so, please explain in the "Additional details" section below)*

## Pre-submit checklist
**Please confirm ALL of the following** before submitting your PR.

- [ ] This PR includes only one addition, removal, or edit.
- [x] I edited the `/data` directory instead of the [README.md](https://github.com/ipfs/awesome-ipfs/blob/master/README.md).
- [x] I reviewed the [content policy](https://github.com/ipfs/awesome-ipfs/blob/master/POLICY.md) and the and the [IPFS Community Code of Conduct](https://github.com/ipfs/community/blob/master/code-of-conduct.md) to ensure my submission meets the requirements.
- [x] I have followed the [CONTRIBUTING.md guidelines](https://github.com/ipfs/awesome-ipfs/blob/master/CONTRIBUTING.md).

### Is there anything else we should know about this PR?
See failing circleci job: https://app.circleci.com/pipelines/github/ipfs/awesome-ipfs/1155/workflows/3a0e7492-db09-4859-8219-d4ac50df169e/jobs/1858?invite=true&invite=true#step-103-298

Issues :-(
> Links 
  1. [L049]  https://cyber.page Failed to open TCP connection to cyber.page:443 (Connection timed out - connect(2) for "cyber.page" port 443)  --- @serejandmyself
  2. [L053] 503 https://www.dreamlink.cloud/  --- @kolessios
  3. [L113] 404 https://github.com/aboutDavid/rocketpad  --- @aboutdavid
  4. [L115] 403 https://www.skiff.com  --- circleci + awesome_bot bug
  5. [L205]  https://imageserver.link Failed to open TCP connection to imageserver.link:443 (Connection timed out - connect(2) for "imageserver.link" port 443) --- @ekumahost

### CODE REVIEW

**Comment by amilich** [comment]
skiff.com is not a 403?

**Comment by SgtPooki** [comment]
@amilich running awesome_bot locally to double check

**Comment by SgtPooki** [comment]
Before this update:

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
49 | Error | https://cyber.page <br> Failed to open TCP connection to cyber.page:443 (Operation timed out - connect(2) for 99.83.154.118:443)
65 | [502](https://httpstatuses.com/502) | https://infinitebooru.com 
113 | [404](https://httpstatuses.com/404) | https://github.com/aboutDavid/rocketpad 
187 | [403](https://httpstatuses.com/403) | https://space.storage/ 
205 | Error | https://imageserver.link <br> Failed to open TCP connection to imageserver.link:443 (Operation timed out - connect(2) for 99.83.154.118:443)


After the changes in this PR:

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
63 | [502](https://httpstatuses.com/502) | https://infinitebooru.com 
183 | [403](https://httpstatuses.com/403) | https://space.storage/ 

added skiff.com back, removed the above two, and now getting No issues :-) locally. Sorry for the noise @amilich

**Comment by amilich** [comment]
> added skiff.com back, removed the above two, and now getting No issues :-) locally. Sorry for the noise @amilich

All good! Thank you :)

**Comment by SgtPooki** [comment]
@sanura-edx FYI that https://infinitebooru.com/ is being removed.

**Pull request merged**
