### PR TITLE
Add Ethereum Blockwatch

### PR DESCRIPTION
**Pull request by MidnightLightning**

### CODE REVIEW

**Comment by RichardLitt** [comment]
Cool. Thanks! @VictorBjelkholm - What do you think about this PR?

**Comment by MidnightLightning** [comment]
Merged upstream again to resolve conflicts. @RichardLitt or @VictorBjelkholm, is this good to go?

**Comment by koalalorenzo** [comment]
This should probably be rebased/updated as it is quiet old!

**Comment by MidnightLightning** [comment]
@koalalorenzo sure, I could update and re-publish again, but this is the second time this has languished. If I go through the effort again, it would be great if this could actually get looked at and resolved!

**Comment by koalalorenzo** [comment]
Are you still maintaining it? Is it anywhere on GitHub?

**Comment by MidnightLightning** [comment]
Okay, @koalalorenzo, this is now rebased, and added both IPFS and GitHub links.

**Comment by koalalorenzo** [comment]
Sweet! thank you!

**Pull request merged**
