### PR TITLE
add article on CIDs in IPFS

### PR DESCRIPTION
**Pull request by PascalPrecht**

### CODE REVIEW

**Comment by koalalorenzo** [comment]
Hi! You need to change the files in `/data` instead of the readme file :)
Could you do that?

**Comment by PascalPrecht** [comment]
Doing it right away!

**Comment by PascalPrecht** [comment]
Done :)

**Comment by koalalorenzo** [comment]
Thank you! 👍

**Comment by gpestana** [comment]
Super nice one again @PascalPrecht 👍 👍

**Pull request merged**
