### PR TITLE
Add IETF RFC Archiving And Indexing Tool 

### PR DESCRIPTION
**Pull request by bonedaddy**
## What kind of PR is this?
**Select only one** *to speed up review/approval; i.e., don't lump an addition and a removal into a single PR.*

- [x] **Adding** something new to awesome-ipfs\

## Pre-submit checklist
**Please confirm ALL of the following** before submitting your PR.

- [x] This PR includes only one addition, removal, or edit.
- [ ] I edited the `/data` directory instead of the [README.md](https://github.com/ipfs/awesome-ipfs/blob/master/README.md).
- [x] I ran the `make build` command following my edits to the `/data` directory.
- [x] I reviewed the [content policy](https://github.com/ipfs/awesome-ipfs/blob/master/POLICY.md) and the and the [IPFS Community Code of Conduct](https://github.com/ipfs/community/blob/master/code-of-conduct.md) to ensure my submission meets the requirements.
- [x] I have followed the [CONTRIBUTING.md guidelines](https://github.com/ipfs/awesome-ipfs/blob/master/CONTRIBUTING.md).

### Is there anything else we should know about this PR?

The current IETF RFC archive linked to in the README is dead in the waters and is 3 years old, and  like 50% of the files listed dont even resolve anymore.

I've created a list that's up-to-date as of yesterday [here](https://gateway.temporal.cloud/ipns/rfcs.temporal.cloud) and it's hosted by Temporal's production IPFS cluster so resolution speeds shouldn't be a problem. If desired I can create a separate PR to link to this DNSLink record which I'll be updating whenever I have free time to download new RFCs, hopefully once a month.

### For new additions: What is your project's *current* size/reach?

Not sure how to answer this. Really it's just a personal tool to add RFCs to IPFS. But it provides a solid tool that will be able to easily scrape new RFCs. 

### For new additions: What is your project's *potential* size/reach?

Whoever cares about reading IETF RFCs

### For new additions: How critical is IPFS to your project?

- [x] Useful, but not critical

### For new additions: What core goal(s) does your project address?

I don't think this really applies to the PR I'm using, but since it relates to Temporal I'll just tick off boxes because why not.

- [x] Big-data solutions
- [x] Data integrity
- [x] Dev tools or other ways to enable developers
- [x] Disaster resilience/recovery
- [x] File storage/retrieval
- [x] File streaming

### Is anything about IPFS blocking your project?

I'm pretty sure everyone in the IPFS community already knows my thoughts about this, so no point in repeating myself.

### CODE REVIEW

**Comment by hsanjuan** [comment]
Funny thing is that I realized we actually already have an RFC archive referenced in the datasets section: https://ipfs.io/ipfs/QmNvTjdqEPjZVWCvRWsFJA1vK7TTw1g9JP6we1WBJTRADM

Should we replace that one? I like that there is tooling to rebuild this one (not sure about the other). The other one seemed to have some sort of search page though which does not seem to work well for me.

@bonedaddy one good thing would be to include in the archive contain a pointer to to the tool it was used to build it.

**Comment by bonedaddy** [comment]
> one good thing would be to include in the archive contain a pointer to to the tool it was used to build it.

You mean in the actual IPFS archive itself? Yea that's definitely a good idea.

> Should we replace that one? I like that there is tooling to rebuild this one (not sure about the other). The other one seemed to have some sort of search page though which does not seem to work well for me.

Well that's entirely up to you all, of course I would be happy to have this archive replace that one, but  either way I have no qualms about whatever option is picked. The previous one certainly has some nicer UX with a search page and all that, and I believe there is a tool to rebuild it.

**Comment by hsanjuan** [comment]
I cannot access rfc-data folder in the existing archive, and the search does not work for me.

WDYT@lidel? should we replace it? Or have 2 of them? I wanted to check if the existing archive uses pdfs or text.

**Comment by bonedaddy** [comment]
>one good thing would be to include in the archive contain a pointer to to the tool it was used to build it.

I've updated the dnslink to include the go cli I used, and updated the little text file to point to the repository that contains the code for the cli. Shouldn't take more than a couple minutes after I post this for the record updates to propagate.

**Comment by hsanjuan** [comment]
@bonedaddy actually I thought you were adding a new archive to the archives section here (with a link). Adding just the tool is no problem. If you were to add the new archive, we can rename the old to something that indicates it's TXTs while yours is PDFs. In the meantime we can add this.

**Pull request merged**
