### PR TITLE
Tools: added ipfs-paste and -screencap

### PR DESCRIPTION
**Pull request by cryptix**

### CODE REVIEW

**Comment by Dignifiedquire** [comment]
Thanks :octocat:

**Comment by harlantwood** [comment]
Yeah! Cool to learn about these.

**Comment by jbenet** [comment]
i use ipfs-screencap with osx + alfred to bind it to `CMD+2`.

**Comment by RichardLitt** [comment]
@jbenet Might be a good idea to upload that Alfred workflow somewhere?

**Pull request merged**
