### PR TITLE
add piln.xyz

### PR DESCRIPTION
**Pull request by fiatjaf**
Piln is a new service that enables seamless (and crowdfunded) pinning of objects on IPFS. It requires no registration, pinning is paid for with Bitcoin over the Lightning Network. All currently pinned objects are public and everybody can extend the pin time of each others' objects. Although this is priced in satoshis and not dollars, the price is much cheaper than other services in the market, but bandwidth is reduced.

https://piln.xyz/

### CODE REVIEW

**Comment by fiatjaf** [comment]
Forgot to mention: if `window.ipfs` is present Piln's dashboard will behave much better.

**Comment by lifeBCE** [comment]
Does it just charge people to store content on the IPFS network? Why wouldn't someone just install an IPFS node themselves as the protocol intends? I think we should be encouraging people to install more nodes to grow the network vs consolidating into fewer nodes but maybe that is just me.

**Comment by balupton** [comment]
>Does it just charge people to store content on the IPFS network? Why wouldn't someone just install an IPFS node themselves as the protocol intends? I think we should be encouraging people to install more nodes to grow the network vs consolidating into fewer nodes but maybe that is just me.

@lifeBCE what happens if you want to share a file and your computer is down, what happens when your computer crashes and you haven't got all the files pinned, what happens when the content was made in the cloud

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hacdias** [comment]
Closing because the service was closed.

**Comment by fiatjaf** [comment]
Just in time.

**Pull request closed without merging**
