### PR TITLE
Update ToC, rename to `Articles and Press`

### PR DESCRIPTION
**Pull request by RichardLitt**
See https://github.com/ipfs/awesome-ipfs/pull/56#discussion_r79292964

### CODE REVIEW

**Comment by VictorBjelkholm** [comment]
`Apps` have to be different to `Single page Webapps`? Should be able to group them together I think

**Comment by RichardLitt** [comment]
They are grouped together; single page webapps is a subcategory.

**Comment by VictorBjelkholm** [comment]
> They are grouped together; single page webapps is a subcategory.

Yeah... Do they have to though? Make something that makes sense would be "Desktop Apps" / "CLI Apps" and "Web Apps". Just don't think it makes sense to divide web apps based on if they are SPAs or not...

**Comment by RichardLitt** [comment]
It may not. Do we think we should divide the other ones up, or just merge it in?

**Comment by VictorBjelkholm** [comment]
No, I think for now we don't have to divide it, since there is not much content and would probably be easier when we have more. For now I think this is fine :+1:

**Pull request merged**
