### PR TITLE
docs: create PR template

### LINKED ISSUE #187: All the new PR are still not populating /data
Even after we made it a little bit more clear to the users in #159, since #130 all the edits on the README have to be made in the `/data` files. This is very much counterintuitive to what the standard `awesome` repositories, and I find it annoying that I have to remember people to do it.

Now I am in solution mode and I should not be: If we could generate the data from the README and enrich it with information/pictures in `/data` it could be a quick win for all the contributors as well as easier to maintain. That is one suggestion. An other one that I had in mind is to decouple the website with this repository and have a scraper taking care of these information.

### PR DESCRIPTION
**Pull request by HugoReeves**
Created a pr template in an effort to resolve #187 
This should ensure changes to the /data folder are made instead of changes to the README.md directly.
The PR template is below.

-------

Does this pull request include an item addition/removal/edit? yes/no

If you answered yes to the previous question, ensure that your answers to the following questions are all yes; otherwise, delete this template and draft your own PR.

Did you edit the `/data` directory instead of the [README.md](https://github.com/ipfs/awesome-ipfs/blob/master/README.md)? yes/no

Does this PR include only one addition/removal/edit? yes/no

Did you run the `make build` command following your edits to the `/data` directory? yes/no

Have you followed the [CONTRIBUTING.md guidelines](https://github.com/ipfs/awesome-ipfs/blob/master/CONTRIBUTING.md)? yes/no

# Details

Provide details of your changes here.

### CODE REVIEW

**Comment by hacdias** [comment]
@HugoReeves thanks for this contribution! I'd just change the questions to checkboxes though. Like this:


- [ ] I did edit edit the `/data` directory instead of the [README.md](https://github.com/ipfs/awesome-ipfs/blob/master/README.md).
- [ ] This PR includes only one addition/removal/edit.
- [ ] I run `make build` command following my edits to the `/data` directory.
- [ ] I followed the [CONTRIBUTING.md guidelines](https://github.com/ipfs/awesome-ipfs/blob/master/CONTRIBUTING.md).

**Comment by HugoReeves** [comment]
@hacdias The template now uses checkboxes.

**Comment by koalalorenzo** [comment]
Why don't we make comments liens for the first section?

```
<!--  
My lines of the PR
--!>
```

In this way we force them to read but it will not appear on every PR. 
It might be a small suggestion, but it is ok to leave those visible!

**Comment by HugoReeves** [comment]
@koalalorenzo I am happy to include the markdown comment. IMO it is better if we have a checkbox that must be ticked by the pr author. This means that when reviewing pr's we can observe that the author has actively agreed that they followed the CONTRIBUTING.md document.

Once this is resolved, is there any further work that needs to be done to have this pr merged?

**Comment by koalalorenzo** [comment]
Thank you! This will help a lot!!

**Pull request merged**
