### PR TITLE
Added webapps

### PR DESCRIPTION
**Pull request by RichardLitt**
See #7.

### CODE REVIEW

**Comment by harlantwood** [comment]
I think the /ipfs links should start with the gateway URL, so they work for everyone...

**Comment by Dignifiedquire** [comment]
agreed on @harlantwood comment

**Comment by RichardLitt** [comment]
Added them.

**Comment by Dignifiedquire** [comment]
LGTM

**Comment by RichardLitt** [comment]
Thanks!

**Pull request merged**
