### PR TITLE
chore: add multiformats tutorial

### PR DESCRIPTION
**Pull request by vasa-develop**
License: MIT
Signed-off-by: Vaibhav Saini <vasa@towardsblockchain.com>

## What kind of change is it?

- [x] Addition
- [ ] Removal
- [ ] Edit
- [ ] Other

### Checklist

- [x] I edited the `/data` directory instead of the [README.md](https://github.com/ipfs/awesome-ipfs/blob/master/README.md).
- [x] This PR includes only one addition/removal/edit.
- [x] I ran the `make build` command following my edits to the `/data` directory.
- [x] I have followed the [CONTRIBUTING.md guidelines](https://github.com/ipfs/awesome-ipfs/blob/master/CONTRIBUTING.md).

## Details

Added an article on Multiformats

### CODE REVIEW

**Comment by vasa-develop** [comment]
@hacdias I have multiple articles that I want to add. How should I do that? Do the Contributing guidelines allow that? I am not sure about them.

**Comment by hacdias** [comment]
@vasa-develop please make a PR for each one so they can be approved sepparatly! How many are they?

**Comment by vasa-develop** [comment]
@hacdias  8 more

**Comment by hacdias** [comment]
@vasa-develop perhaps you could bundle the most related ones in single PRs

**Comment by vasa-develop** [comment]
@hacdias  Ok, I will batch the articles in 2 PRs.

**Pull request merged**
