### PR TITLE
Add "IPFS-Shrinkwrap" tool.

### PR DESCRIPTION
**Pull request by johnhenry**

### CODE REVIEW

**Comment by johnhenry** [comment]
You got it!

**Comment by VictorBjelkholm** [comment]
@johnhenry Hey! Cool idea, seems like it can really be helpful. However, I did hit some issues trying it out.

* [ ] Path to node is hardcoded instead of asking the environment for it ( https://github.com/elsehow/ipfs-shrinkwrap/blob/5cfc3f9e10f7e62646e21acefb124d9c0700f70a/cmd.js#L1 ) For example, my node is installed in my home folder, so I couldn't run the tool before changing this to `/usr/bin/env node`

* [ ] There is no output when I run ipfs-shrinkwrap after installing, not sure what's going on, didn't get any output after 1m+ of running, so exited it from there. Should probably add some sort of progress/feedback to the user

* [ ] Haven't really digged into it but "The hash will point to whatever the contents of your node_modules/ directory were at the time the shrinkwrap was done" worried me, since running `npm install a-module` and then `ipfs add -r node_modules/a-module` is never gonna return the same hash, npm adds bunch of metadata like where the package is coming from and also timestamp of installation. Make sure you can have a atomic way of getting the packages. Maybe this doesn't actually affect `ipfs-shrinkwrap`

**Comment by johnhenry** [comment]
Apologies, @VictorBjelkholm, I should have vetted this more thoroughly. I will be sure to do so in the future. :)

**Comment by RichardLitt** [comment]
@VictorBjelkholm Would you be OK with merging this, after your points are met?

**Comment by VictorBjelkholm** [comment]
@RichardLitt Probably, depends. As it is right now, it's not working so can't judge really.

**Comment by RichardLitt** [comment]
Ok. Reopen this when it is working again. :)

**Pull request closed without merging**
