### PR TITLE
add ipfs-mount tool

### PR DESCRIPTION
**Pull request by richardschneider**

### CODE REVIEW

**Comment by Kubuxu** [comment]
If you could mention that it is windows tool, it would be great.

**Comment by richardschneider** [comment]
@Kubuxu The description is "Mount IPFS as a mapped drive on Windows"; isn't that  what you want?

**Comment by Kubuxu** [comment]
It was more about the link/name, we plan extracting the FUSE base mount tool from the go-ipfs under the same name.
So maybe linking it as `[ipfs-mount] for Windows` would be better.
@RichardLitt could you help me with this one, I might be biased.

**Comment by RichardLitt** [comment]
I think it works fine. I don't think that it is unnecessarily confusing.

**Pull request merged**
