### PR TITLE
Added VIPFS

### PR DESCRIPTION
**Pull request by midzdotdev**
Added VIPFS to tools.yaml

For @Ideea-inc who created this cool project

### CODE REVIEW

**Comment by lidel** [comment]
@james2mid thank you!

Do you mind updating README? (run `npm ci && npm run build:readme` and commit produced updates)

**Comment by lidel** [comment]
ping @james2mid

**Comment by andrew** [comment]
The readme no longer needs updating (it happens automatically) but there is a conflict in the tools.yaml file that is preventing this from being merged

**Comment by SgtPooki** [comment]
Replacing with https://github.com/ipfs/awesome-ipfs/pull/431

**Pull request closed without merging**
