### PR TITLE
Added clarification about already built stuff

### PR DESCRIPTION
**Pull request by RichardLitt**
Some people were confused by this. Cf. https://github.com/ipfs/community/issues/69. This text should help!

### CODE REVIEW

**Comment by Dignifiedquire** [comment]
Thanks, can you add some line breaks please? (just for the code, I like 80 char limit ;))

**Comment by RichardLitt** [comment]
This is a Readme repo. Is that really necessary? :/

**Comment by Dignifiedquire** [comment]
Thanks :)

**Comment by jbenet** [comment]
I'd vote for either adding a commit hook + test that forces a style or
being more laissez faire

On 80 chars thing-- markdown actually makes it hard links often break it so
it often doesn't make sense to enforce

**Pull request merged**
