### PR TITLE
feat: add DolphinServiceMenu to apps.yaml

### PR DESCRIPTION
**Pull request by amar-laksh**
adding a Dolphin Service Menu to upload files to IPFS!

### CODE REVIEW

**Comment by koalalorenzo** [comment]
Isn't using globalupload.io a little far from decentralisation?

I bet we can integrate with [Siderus Orion](https://orion.siderus.io), or any local IPFS node to have a more decentralised experience.

**Comment by amar-laksh** [comment]
> Isn't using globalupload.io a little far from the purpose of decentralisation?
> 
> I bet we can integrate with [Siderus Orion](https://orion.siderus.io), or any local IPFS node to have a more decentralised experience.

Well, I wasn't aware of the Orion Project (thanks for that!). The main advantage of using an external service like globalupload is that we really don't have to rely on a local IPFS node running on our system. (I hope you can see how that might be convenient for the average user). 

Thanks for the suggestion anyways!

**Comment by hacdias** [comment]
Hello @amar-laksh, is this project still active?

**Comment by amar-laksh** [comment]
> Hello @amar-laksh, is this project still active?

Well yes :)

**Pull request merged**
