### PR TITLE
Add dillo-ipfs

### PR DESCRIPTION
**Pull request by clehner**
`dillo-ipfs` is a plugin for the Dillo web browser that adds support for IPFS URLs.

Site: https://ipfs.io/ipns/12D3KooWBG1fsFRF4ykpidXVNVnbon5KLfv67pkkGeFstrwftVVb/

### CODE REVIEW

**Comment by koalalorenzo** [comment]
Hey! Do you have a GitHub link?

**Comment by clehner** [comment]
@koalalorenzo No GitHub link; this is for the decentralized web, happily hosted on IPFS and git-ssb

**Comment by koalalorenzo** [comment]
Good,
My opinion is that the source code should not start from a single point of failure: like your computer.

My suggestion is to also open a GitHub repo in case the ipfs hash doesn't get pinned anywhere (or the pin is lost in time)

**Comment by clehner** [comment]
@koalalorenzo I've updated it to link to the source on git.scuttlebot.io instead. Is that acceptable?

**Comment by koalalorenzo** [comment]
You can add both, that was my intention \o/

**Comment by koalalorenzo** [comment]
The only problem that I see is that the IPNS is not resolving... But that is IPNS. Merging.

**Pull request merged**
