### PR TITLE
Added solid-ipfs

### PR DESCRIPTION
**Pull request by leinue**
[solid-ipfs](https://github.com/Eximua/solid-ipfs) - Using [Solid](https://solid.inrupt.com) to store IPFS Hash privately or publicly

### CODE REVIEW

**Comment by leinue** [comment]
Can this be accepted as soon as possible ?

**Comment by koalalorenzo** [comment]
I am not able to test this that is why I am not able to merge this and verify how it works. 

Can you give more info about how it works? What is the meaning behind "Using Solid to store IPFS Hash"?

**Comment by leinue** [comment]
You can click [here](https://solid.inrupt.com/) to learn more about **Solid**.

[solid-ipfs](https://github.com/eximua/solid-ipfs) can privatize the hash of the IPFS file, which prevents the hash value from being leaked (this is useful if the user doesn't want to expose the hash)

**Comment by leinue** [comment]
[Solid](https://solid.inrupt.com) is part of the Semantic web and its purpose is to give data ownership to the user. If the user wants to privatize the file to the IPFS network, then storing the Hash in the Solid network (with permission control, WAC, web access control) is a very good measure.

**Comment by leinue** [comment]
Solid uses RDF (Resource Definition Framework) to define all real-world resources, including but not limited to folders, files, chats, code, and more. So we think of the hash of an IPFS file as a file resource stored in RDF. This adds Solid's semantic calculations (in fact, a graph calculation) and WAC (Web Access Control) to implement privatized storage of hashes.

**Comment by koalalorenzo** [comment]
So It works as IPNS / DNSLINK alternative?
How do you ensure WAC / private content on IPFS when the hashes are public? are you encrypting those? Do you have any suggestion on how to test it?

**Comment by leinue** [comment]
1. Can be understood as an alternative to IPNS / DNSLINK.
2. WAC is a very strict privilege control specification and generally cannot cause a leak.
3. This version does not encrypt the hash, but encryption is really necessary.
4. Are the tests you refer to as automated tests or human tests?

**Comment by koalalorenzo** [comment]
I want to test this later this evening, how can I open the app and use it? 
Do I need a Solid Pod?

**Comment by leinue** [comment]
@koalalorenzo Yes, you need a Solid Pod, please click [here](https://solid.authing.cn/register) to register.
Then follow the steps below to test:

1. clone [solid-ipfs](https://github.com/Eximua/solid-ipfs)
2. [Get a Solid Pod](https://solid.authing.cn/register) and [login](https://solid.authing.cn/login)
3. Change the url parameter of line 20 of this [file](https://github.com/Eximua/solid-ipfs/blob/master/examples/index.html) to your address after registration, which is to replace `alicea` with your solid pod username.
4. Start http-server at the root of project `solid-ipfs` and visit <YOUR_URL>/example
5. Open the browser console, if the output "保存成功" means successful execution
6. Visit `https://<YOUR_USERNAME>.solid.authing.com/inbox/` to check if the folder has the `/ipfs/hash/` directory and the corresponding file in the directory (test stored hash is `xxxxxxaaaaaa`). Or visit `https://<YOUR_USERNAME>.solid.authing.cn/inbox/ipfs/hash/xxxxxxaaaaaa.txt` to see if it can be opened.

**Comment by leinue** [comment]
hello, @koalalorenzo, have you tested it ?

**Comment by leinue** [comment]
oh my god

**Comment by koalalorenzo** [comment]
Hi,
I am sorry for the delay. No I have not tested it yet as it takes a lot of time and I am not a support/getting paid for this. I am reviewing PRs to help the community and the ecosystem, so please be patient. I am going to drop this and hopefully somebody else will review it.

Please, please, please. Understand that I am doing this for free and I am very busy! Don't treat me badly for it! 😢

**Comment by koalalorenzo** [comment]
small note: Read the README how to update, I see you modified just the README itself and this change will be removed on the next PR if you don't do it properly!

**Comment by leinue** [comment]
@koalalorenzo I got it, thank you!

**Comment by SgtPooki** [comment]
Closing. This PR should be re-opened and the entry should modify the appropriate file in the `data` folder only.

**Comment by SgtPooki** [comment]
pinging @leinue for visibility.

**Pull request merged**
