### PR TITLE
Addition of Pedity in awesome-ipfs list

### PR DESCRIPTION
**Pull request by PedityOfficial**
Added Pedity in the awesome-ipfs list.

Pedity is first decentralized content rewards platform on stellar. Powerful features including content sharing, blogging, stellar profiles.

### CODE REVIEW

**Comment by koalalorenzo** [comment]
I was not able to find any information on how Pedity is using IPFS and in the alpha it looks that the images/content are still uploaded to Imgur or other sources, not IPFS.

Where is the source code so I can have a look at it?

**Comment by koalalorenzo** [comment]
We can wait for the source code probably :)

**Comment by koalalorenzo** [comment]
No it is not required AFAIK, but I am curious about the IPFS integration as I can't check it yet. If somebody wants to add few cents they are more than welcome! 😃

**Comment by PedityOfficial** [comment]
@koalalorenzo 
I will try to explain it more, we will check a particular post (https://pedity.com/article/54151f44a68e3da81efb89754d1d5c292bfc2054eb4fd07bd70db1f5788e1303) created by Address(GBU4HMAZXRZJPHJVAYVTWQBSVNFSIZ2VN3WXOB3M37BP5IGUS5GDOIHS)

We are using following library go-ipfs-api, go-cid, go-multihash
54151f44a68e3da81efb89754d1d5c292bfc2054eb4fd07bd70db1f5788e1303 is transaction id 

Let's check this transaction for instance which is created through pedity platform.
http://testnet.stellarchain.io/tx/54151f44a68e3da81efb89754d1d5c292bfc2054eb4fd07bd70db1f5788e1303

Memo hash - 2XKc8RHu+uHJmuKvCd9MmUzZ/CXN/HA1VRRbKEuSLPo=
We are using sha2-256 multihash where digest is 32byte
Stellar Memo hash contains 32 byte of data hence we send digest in the memo hash and while decoding we add the 1220 as we are using sha2-256.
Decoding this from base64 and adding 0x12 0x20 in the beginning gives - 1220d9729cf111eefae1c99ae2af09df4c994cd9fc25cdfc703555145b284b922cfa

Encoding the base58 data we get QmcyUYXLXHUqEbmo8pt17LfeqSVxj39V8uxRcrzSbqcsx5
Which bring the content - https://ipfs.io/ipfs/QmcyUYXLXHUqEbmo8pt17LfeqSVxj39V8uxRcrzSbqcsx5
You can see this here -
https://pedity.com/article/54151f44a68e3da81efb89754d1d5c292bfc2054eb4fd07bd70db1f5788e1303

**Comment by PedityOfficial** [comment]
@koalalorenzo 
Any response on this PR ?
More commits has been on PR so some checks have failed now.
Hope we can close this soon.

**Comment by koalalorenzo** [comment]
There are some conflicts in your PR.
I am not confident in merging things that I cannot test / verify or where I don't have source code (depends on the cases) :(
 
Usually somebody from Protocol Labs can help, but they are busy taking care of more important tasks.

**Comment by PedityOfficial** [comment]
I believe conflicts are because of new updates in data/apps.yaml
None the less, do you think a document or article about how pedity works will be good for explanation about how Pedity uses IPFS and stellar so that we can close this?

**Comment by andrew** [comment]
Looks like https://pedity.com is now https://tree3.network which I just merged

**Pull request closed without merging**
