### PR TITLE
BrainWash dataset added

### PR DESCRIPTION
**Pull request by tonuonu**
## What kind of change is it?

- [x] Addition
- [ ] Removal
- [ ] Edit
- [ ] Other

### Checklist

- [x] I edited the `/data` directory instead of the [README.md](https://github.com/ipfs/awesome-ipfs/blob/master/README.md).
- [x] This PR includes only one addition/removal/edit.
- [x] I ran the `make build` command following my edits to the `/data` directory.
- [x] I have followed the [CONTRIBUTING.md guidelines](https://github.com/ipfs/awesome-ipfs/blob/master/CONTRIBUTING.md).

## Details

Added dataset of https://purl.stanford.edu/sx925dc9385 known under name BrainWash.

### CODE REVIEW

**Comment by tonuonu** [comment]
CrowdHuman dataset added too

**Comment by lidel** [comment]
Hi @tonuonu, are you still hosting those datasets? Or know PeerID that has them?

**Comment by tonuonu** [comment]
Yes, I do host. 

$ ipfs pin ls -t recursive | grep QmZ8BpYCtcPeA5g6uXciNXN395WeqZYNVNvz4xvBxsfxqy
QmZ8BpYCtcPeA5g6uXciNXN395WeqZYNVNvz4xvBxsfxqy recursive
$ ipfs id
{
        "ID": "QmNfdGhdhqaGq6q5aLp4SJhLMqq9JYv3EU1QZfH9TRXDQh",
        "PublicKey": "CAASpgIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCdL9ZePhaMDpp81a7qDWx4UbxYW1eCCTl9ObwVys2jPFcrj+AIWCVz9Gfp9BURfjkLWjp9eXUb1NyoWmOeQp3EZRmkw3Gbrjbe7D56vt2MLqMmQMJnYotqfNDRn0M5ygwJ3WkQcGVnHPMlP4fiLj7vGABk/ITodzLLAnmJiFp0iqoSRBwnZehunk3Nb3LOqQ04h1mBv8eiWVirn2oCsYx3Fcz/Ut1dateKYL/BWkuN9ywVzbBselsQkxUs9phKPuFvfQYn9CE6sMxVp7eo2f6j6hug+e3Su7atqqQEJDpEteK2w/sTqfAeWFteP9L99Opn7UyO2z//uf0T/EBJvKr5AgMBAAE=",
        "Addresses": [
                "/ip6/::1/tcp/4001/ipfs/QmNfdGhdhqaGq6q5aLp4SJhLMqq9JYv3EU1QZfH9TRXDQh",
                "/ip6/2001:7d0:4280:480:329c:23ff:fec8:c335/tcp/4001/ipfs/QmNfdGhdhqaGq6q5aLp4SJhLMqq9JYv3EU1QZfH9TRXDQh",
                "/ip4/127.0.0.1/tcp/4001/ipfs/QmNfdGhdhqaGq6q5aLp4SJhLMqq9JYv3EU1QZfH9TRXDQh",
                "/ip4/192.168.1.203/tcp/4001/ipfs/QmNfdGhdhqaGq6q5aLp4SJhLMqq9JYv3EU1QZfH9TRXDQh"
        ],
        "AgentVersion": "go-ipfs/0.4.22/",
        "ProtocolVersion": "ipfs/0.1.0"
}

$ 

I think IPFS should find it anyway, no Peer ID really needed.

    Tonu

**Comment by tonuonu** [comment]
Also
$ ipfs pin ls -t recursive | grep QmTgBpFRM1K4gGyLKSv7tJnEkZZcEQcswnGDdBYkCRu6Vw
QmTgBpFRM1K4gGyLKSv7tJnEkZZcEQcswnGDdBYkCRu6Vw recursive

and others I submitted here.

**Comment by tonuonu** [comment]
> @tonuonu thank you! Do you mind rebasing this PR so we can merge it?

Done. Sorry for delay, busy times.

**Comment by tonuonu** [comment]
> How is PSY - Gangnam Style relevant to IPFS?

This is one of most popular music videos ever and it is important to have clear demo case of pop music demo on awesome.ipfs.io. I thought AWESOME.ipfs.io is about showing IPFS's every aspect. Correct me if I am wrong. AFAIK awesome.ipfs.io is not only about platform for IPFS developers but includes samples of different usages available - databases, datasets, messaging, historic archives etc.

**Pull request merged**
