### PR TITLE
Added Arbore

### PR DESCRIPTION
**Pull request by cryptix**
@michaelMure are you fine with adding it?

### CODE REVIEW

**Comment by MichaelMure** [comment]
Totally !

**Comment by cryptix** [comment]
Nice! I messed up the link, though...

**Comment by MichaelMure** [comment]
There is also http://arbo.re ;-p

**Comment by Dignifiedquire** [comment]
How ready is this? (not that this does not look awesome, but if it's not usable yet I'd rather wait so people are not disappointed when they want to use it)

**Comment by MichaelMure** [comment]
For now, it's close to a download manager on top of IPFS. That is, it lacks:
- the ability to add new content to ipfs
- contact management / encryption (should come with IPFS's keystore)
- notification (should come with IPFS's pub/sub)

Le 6 nov. 2015 23:02, "Friedel Ziegelmayer" <notifications@github.com> a
écrit :

**Comment by jbenet** [comment]
@MichaelMure take screenshots and maybe a demo video!

**Comment by RichardLitt** [comment]
@MichaelMure How is it now? :D

**Comment by RichardLitt** [comment]
@MichaelMure @cryptix Let's reopen this when it is useable. :)

**Pull request closed without merging**
