### PR TITLE
feat: clean up (a lot)

### PR DESCRIPTION
**Pull request by hacdias**
1. Updates the dependencies to the latest.
2. Cleans up the code... A lot! And it could _still_ be improved.

### CODE REVIEW

**Comment by koalalorenzo** [comment]
No more Makefile 😱 

Would be nice to have it at least

**Comment by hacdias** [comment]
@koalalorenzo ah, ugh, well... I can add it again. We just had it because it was required on jenkins :P

**Comment by koalalorenzo** [comment]
@hacdias could you add it again? It will help a lot!

**Comment by hacdias** [comment]
I did :)

**Pull request merged**
