### PR TITLE
Added http2ipfs (and testing GitCop)

### PR DESCRIPTION
**Pull request by RichardLitt**
Testing GitCop

### CODE REVIEW

**Comment by GitCop** [comment]
Oh noes! There were the following issues with your PR

 * Commit: 99a9bfe8e24a324367cd686257561e0838d00048
  * Your commit message does not contain a body

Guidelines are available at https://github.com/ipfs/awesome-ipfs/blob/master/CONTRIBUTING.md.

---
This message was auto-generated by https://gitcop.com

**Comment by RichardLitt** [comment]
Ah, ok. I was trying to see if I could use the default GitCop to wrap at 80 chars. Looks like I'll have to experiment a bit more to make this work.

**Comment by Dignifiedquire** [comment]
@RichardLitt I think a good pre-commit hook would be much more valuable, especially as it would be much more configurable

**Comment by RichardLitt** [comment]
@Dignifiedquire agreed! Let's talk about it in an issue.

**Comment by jbenet** [comment]
it's going to _suck_ when links are >80 chars and they _force_ lines to be longer.

**Comment by RichardLitt** [comment]
Agreed. Mostly I was just seeing what gitcop can do. 

Someone want to check the actual content of this PR?

**Comment by Dignifiedquire** [comment]
content looks good

**Comment by RichardLitt** [comment]
Thanks.

**Pull request merged**
