### PR TITLE
add Testcorpus for Image Compression Algoritms

### PR DESCRIPTION
**Pull request by RubenKelevra**
## What kind of PR is this?
- [x] **Adding** something new to awesome-ipfs

## Pre-submit checklist

- [x] This PR includes only one addition, removal, or edit.
- [x] I edited the `/data` directory instead of the [README.md](https://github.com/ipfs/awesome-ipfs/blob/master/README.md).
- [x] I ran the `make build` command following my edits to the `/data` directory.
- [x] I reviewed the [content policy](https://github.com/ipfs/awesome-ipfs/blob/master/POLICY.md) and the and the [IPFS Community Code of Conduct](https://github.com/ipfs/community/blob/master/code-of-conduct.md) to ensure my submission meets the requirements.
- [x] I have followed the [CONTRIBUTING.md guidelines](https://github.com/ipfs/awesome-ipfs/blob/master/CONTRIBUTING.md).

### Is there anything else we should know about this PR?
The data in this dataset has been manually collected and reviewed by me.

It's planned to be used for JPEG-XL encoder/decoder commit verifications.

### For new additions: What is your project's *current* size/reach?
undetermined

### For new additions: What is your project's *potential* size/reach?
undetermined

### For new additions: How critical is IPFS to your project?

- [x] Essential
- [ ] Somewhat critical
- [ ] Useful, but not critical

### For new additions: What core goal(s) does your project address?

- [ ] Big-data solutions
- [ ] Freedom from corporate/government interference
- [x] Data integrity
- [x] Dev tools or other ways to enable developers
- [x] Disaster resilience/recovery
- [x] File storage/retrieval
- [ ] File streaming
- [x] Permanent archiving
- [ ] Self-sovereign idenity
- [ ] Platforms that utilize consensus, reputation, or incentivization
- [ ] Other *(please list)*

### Is anything about IPFS blocking your project?
no

### CODE REVIEW

**Comment by andrew** [comment]
@RubenKelevra do you have a more permanent link than to a tweet that can be used?

**Comment by RubenKelevra** [comment]
Currently not, I'll exchange the link as soon as there's a Readme somewhere :)

**Comment by SgtPooki** [comment]
@RubenKelevra any update here?

**Comment by RubenKelevra** [comment]
> @RubenKelevra any update here?

Yeah I decided to put it on Github because ipfs had performance issues dunno why.

Around half of the commons folder is already added with proper attribution:

https://github.com/RubenKelevra/rk_image_set

**Comment by RubenKelevra** [comment]
Once it's completed there I like to push the whole repo to ipfs again, so it can be fetched from ipfs or from github. :)

**Comment by SgtPooki** [comment]
Ok great I updated the PR but you should probably add a bit more info to the repo though. (like a link to https://twitter.com/RubenKelevra/status/1236525895000653824 )

**Comment by 2color** [comment]
Closing as we no longer have datasets in this repo

**Pull request closed without merging**
