### PR TITLE
add filemap.xyz screenshot.

### PR DESCRIPTION
**Pull request by fiatjaf**
filemap.xyz is already there on the list. I'm just uploading a very small screenshot.

### CODE REVIEW

**Comment by VictorBjelkholm** [comment]
Thanks! Looks way better :)

Could you do a rebase? readme should contain no changes here I think.

**Comment by fiatjaf** [comment]
I've just run `npm run build:readme` as instructed. If I run a rebase and run that script again the results will be the same.

**Comment by hacdias** [comment]
It seems I can't rebase the PR since the forked repository doesn't exist anymore. I'm going to close this. You're more than welcome to submit this again 😃

**Comment by fiatjaf** [comment]
Blablabla, same stuff.

**Pull request closed without merging**
