### PR TITLE
DeCommerce - Decentralized ecommerce for web3. I would like to add my project into the list.

### PR DESCRIPTION
**Pull request by jozefpinter**
## What kind of PR is this?
**Select only one** *to speed up review/approval; i.e., don't lump an addition and a removal into a single PR.*

- [x] **Adding** something new to awesome-ipfs
- [N/A] **Editing** something already listed on awesome-ipfs
- [N/A] **Removing** something from awesome-ipfs
- [N/A] **Something else** *(if so, please explain in the "Additional details" section below)*

## Pre-submit checklist
**Please confirm ALL of the following** before submitting your PR.

- [x] This PR includes only one addition, removal, or edit.
- [x] I edited the `/data` directory instead of the [README.md](https://github.com/ipfs/awesome-ipfs/blob/master/README.md).
- [x] I reviewed the [content policy](https://github.com/ipfs/awesome-ipfs/blob/master/POLICY.md) and the and the [IPFS Community Code of Conduct](https://github.com/ipfs/community/blob/master/code-of-conduct.md) to ensure my submission meets the requirements.
- [x] I have followed the [CONTRIBUTING.md guidelines](https://github.com/ipfs/awesome-ipfs/blob/master/CONTRIBUTING.md).

### Is there anything else we should know about this PR?

- [x] **No**

### For new additions: What is your project's *current* size/reach?

- [x] **100** downloads

### For new additions: What is your project's *potential* size/reach?

- [x] **10000** downnloads

### For new additions: How critical is IPFS to your project?

- [ ] Essential
- [x] Somewhat critical
- [ ] Useful, but not critical

### For new additions: What core goal(s) does your project address?

- [ ] Big-data solutions
- [ ] Freedom from corporate/government interference
- [ ] Data integrity
- [ ] Dev tools or other ways to enable developers
- [ ] Disaster resilience/recovery
- [ ] File storage/retrieval
- [ ] File streaming
- [ ] Permanent archiving
- [ ] Self-sovereign identity
- [ ] Platforms that utilize consensus, reputation, or incentivization
- [x] Other *(please list)*
* e-commerce

### Is anything about IPFS blocking your project?
- [x] **No**

### CODE REVIEW

**Comment by SgtPooki** [comment]
@jozefpinter can you please finish filling out the PR template in the description?

**Comment by jozefpinter** [comment]
> @jozefpinter can you please finish filling out the PR template in the description?

@SgtPooki I think the PR description is filled out. Am I missing something?

**Comment by SgtPooki** [comment]
There are questions under additional details left blank. Would you mind being awesome and filling them out?

**Comment by jozefpinter** [comment]
> There are questions under additional details left blank. Would you mind being awesome and filling them out?

**Comment by jozefpinter** [comment]
> There are questions under additional details left blank. Would you mind being awesome and filling them out?

@SgtPooki Is it okay this way? Please take a look.

**Comment by jozefpinter** [comment]
OK

**Comment by SgtPooki** [comment]
> > There are questions under additional details left blank. Would you mind being awesome and filling them out?
> 
> @SgtPooki Is it okay this way? Please take a look.

That's great, thank you!

**Comment by SgtPooki** [comment]
CI is passing, but danger workflow isn't [working properly](https://github.com/ipfs/awesome-ipfs/actions/runs/3146587462/jobs/5115210333#step:7:27). Debugging on this PR prior to merging.

**Pull request merged**
