### PR TITLE
Added Terrive to data/apps

### PR DESCRIPTION
**Pull request by appukuttan66**
## What kind of PR is this?
**Select only one** *to speed up review/approval; i.e., don't lump an addition and a removal into a single PR.*

- [x] **Adding** something new to awesome-ipfs
- [ ] **Editing** something already listed on awesome-ipfs
- [ ] **Removing** something from awesome-ipfs
- [ ] **Something else** *(if so, please explain in the "Additional details" section below)*

## Pre-submit checklist
**Please confirm ALL of the following** before submitting your PR.

- [x] This PR includes only one addition, removal, or edit.
- [x] I edited the `/data` directory instead of the [README.md](https://github.com/ipfs/awesome-ipfs/blob/master/README.md).
- [x] I reviewed the [content policy](https://github.com/ipfs/awesome-ipfs/blob/master/POLICY.md) and the and the [IPFS Community Code of Conduct](https://github.com/ipfs/community/blob/master/code-of-conduct.md) to ensure my submission meets the requirements.
- [x] I have followed the [CONTRIBUTING.md guidelines](https://github.com/ipfs/awesome-ipfs/blob/master/CONTRIBUTING.md).

### Is there anything else we should know about this PR?

Nope.

### For new additions: What is your project's *current* size/reach?

It's just been a few weeks and i haven't been able to promote much. So, number of users => 3 , frequency of posts => every 2 or 3 days.

### For new additions: What is your project's *potential* size/reach?

N/A

### For new additions: How critical is IPFS to your project?

- [ ] Essential
- [ ] Somewhat critical
- [x] Useful, but not critical

### For new additions: What core goal(s) does your project address?

- [ ] Big-data solutions
- [x] Freedom from corporate/government interference
- [x] Data integrity
- [ ] Dev tools or other ways to enable developers
- [ ] Disaster resilience/recovery
- [x] File storage/retrieval
- [x] File streaming ( *HLS streaming is planned* )
- [ ] Permanent archiving
- [x] Self-sovereign identity
- [x] Platforms that utilize consensus, reputation, or incentivization
- [ ] Other *(please list)*

### Is anything about IPFS blocking your project?

Load times for MP4 are horrible, planning to switch over to HLS streaming

### CODE REVIEW

**Comment by andrew** [comment]
Looks like you've only added an image in this pr, you also need to add details in the correct file in the `/data` directory

**Comment by appukuttan66** [comment]
@andrew , Sorry my bad ! I made the changes but i forgot to commit x_x

**Comment by appukuttan66** [comment]
@andrew sorry to ping you like this, but just found out about a typo :

Corrected one,
https://github.com/appukuttan66/awesome-ipfs/blob/e57e49c86af986596ecfe7784cd8607b04961c1f/data/apps.yaml#L496

Again, i apologize for this

**Comment by andrew** [comment]
@appukuttan66 can you open another pr?

**Comment by appukuttan66** [comment]
Done ! #390

**Pull request merged**
