### PR TITLE
Add Unstoppable Domains App

### PR DESCRIPTION
**Pull request by PaulUD**
## What kind of change is it?

- [X] Addition
- [ ] Removal
- [ ] Edit
- [ ] Other

### Checklist

- [x] I edited the `/data` directory instead of the [README.md](https://github.com/ipfs/awesome-ipfs/blob/master/README.md).
- [X] This PR includes only one addition/removal/edit.
- [x] I ran the `make build` command following my edits to the `/data` directory.
- [X] I reviewed the [content policy](POLICY.md) to ensure my submission meets the requirements.
- [X] I have followed the [CONTRIBUTING.md guidelines](https://github.com/ipfs/awesome-ipfs/blob/master/CONTRIBUTING.md).

## Details

Added the Unstoppable Domains app which is the ability to connect your blockchain domain with an IPFS hash to build a censorship resistant website. Also added unstoppable-domains-app.png file to /src/static/images folder.

### CODE REVIEW

**Comment by PaulUD** [comment]
@Stebalien @lidel 

Hi Martin,

Please contact me via [my profile](https://github.com/PaulUD) if you require any details as part of your review for this pull request.

Thanks

Paul

**Comment by PaulUD** [comment]
@lidel what two steps do you require Martin?

**Comment by lidel** [comment]
@PaulUD  Unchecked items from your post at https://github.com/ipfs/awesome-ipfs/pull/309#issue-370717983, namely: adding your app to manifest in `data/` directory and then running build which generates README and the website.

Let me know if you have any issues.

**Comment by PaulUD** [comment]
@lidel so it's not an option of amending the README.md OR the /data directory?

**Comment by PaulUD** [comment]
@lidel amended /data/apps.yaml reverted README.md to original and checked additional 2 items in the checklist.

**Comment by lidel** [comment]
Thank you @PaulUD,  do you mind moving it from `apps.yml` to `services.yml` ?
It sounds like its a better place for it.

**Comment by PaulUD** [comment]
@lidel moved from Apps to Services as requested.

**Pull request merged**
