### PR TITLE
feat: add ipfscloud

### PR DESCRIPTION
**Pull request by josselinchevalay**
follow this thread on discuss https://discuss.ipfs.io/t/ipfscloud-a-decentralised-cloud-storage-platform/3847

### CODE REVIEW

**Comment by vasa-develop** [comment]
Check out the new interface for IpfsCloud: http://ipfscloud.store. 
Know more here: http://clusterlabs.io/#projects

**Comment by josselinchevalay** [comment]
@vasa-develop are you ok with that now ?

**Comment by vasa-develop** [comment]
@josselinchevalay Yeah.

**Comment by josselinchevalay** [comment]
@koalalorenzo for @vasa-develop and me is ok? is ok for you ? 

Regards

**Comment by vasa-develop** [comment]
@koalalorenzo is there any problem in adding this PR? If not, can you please merge it?

**Comment by vasa-develop** [comment]
@josselinchevalay Sorry to bug you again, but can you figure out what is wrong with the integration. I am not much familiar with this stuff.

Thanks!

**Comment by josselinchevalay** [comment]
@vasa-develop  @koalalorenzo this fail by a node timeout. @koalalorenzo  can you help we on that ? 

Regards

**Pull request merged**
