### PR TITLE
Add IPFSBay

### PR DESCRIPTION
**Pull request by IPFSBay**
Unstoppable marketplace in the IPFS network.

## What kind of PR is this?
**Select only one** *to speed up review/approval; i.e., don't lump an addition and a removal into a single PR.*

- [x] **Adding** something new to awesome-ipfs
- [ ] **Editing** something already listed on awesome-ipfs
- [ ] **Removing** something from awesome-ipfs
- [ ] **Something else** *(if so, please explain in the "Additional details" section below)*

## Pre-submit checklist
**Please confirm ALL of the following** before submitting your PR.

- [x] This PR includes only one addition, removal, or edit.
- [x] I edited the `/data` directory instead of the [README.md](https://github.com/ipfs/awesome-ipfs/blob/master/README.md).
- [x] I reviewed the [content policy](https://github.com/ipfs/awesome-ipfs/blob/master/POLICY.md) and the and the [IPFS Community Code of Conduct](https://github.com/ipfs/community/blob/master/code-of-conduct.md) to ensure my submission meets the requirements.
- [x] I have followed the [CONTRIBUTING.md guidelines](https://github.com/ipfs/awesome-ipfs/blob/master/CONTRIBUTING.md).

### For new additions: How critical is IPFS to your project?

- [ ] Essential
- [ ] Somewhat critical
- [ ] Useful, but not critical

### For new additions: What core goal(s) does your project address?

- [ ] Big-data solutions
- [x] Freedom from corporate/government interference
- [ ] Data integrity
- [ ] Dev tools or other ways to enable developers
- [ ] Disaster resilience/recovery
- [x] File storage/retrieval
- [ ] File streaming
- [ ] Permanent archiving
- [ ] Self-sovereign identity
- [ ] Platforms that utilize consensus, reputation, or incentivization
- [ ] Other *(please list)*

### CODE REVIEW

**Comment by hsanjuan** [comment]
You haven't added the picture file `    picture: /images/ipfsbay.png`

**Review by IPFSBay — COMMENTED** [review]
logo

**Comment by IPFSBay** [comment]
Hello.
Image just added.

Thank you.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Review by lidel — CHANGES_REQUESTED** [review]
<del>@IPFSBay please include this image as part of your  PR under `/src/static/images` </del>

nvm, i see you did that in https://github.com/ipfs/awesome-ipfs/pull/416

**Review by lidel — APPROVED** [review]

**Comment by IPFSBay** [comment]
Hello.
Thank you for a reply.

Yes, I know that logo is not included, because the repository tell me:
Uploads are disabled. File uploads require push access to this repository.

This error is maybe on my side, I am not sure.
Please, be so kind and use this logo: https://ipfsbay.com/images/logo.png

Thank you very much.

Team IPFSBay

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Pull request merged**
