### PR TITLE
Added app DtinyUrl

### PR DESCRIPTION
**Pull request by facert**
Dcentralized url shortening service base on ipfs

### CODE REVIEW

**Comment by hacdias** [comment]
Hello @facert! Could you explain us how it works?

**Comment by facert** [comment]
hello @hacdias , DtinyUrl  is wrapped in a small HTML document with a JavaScript that redirects to the desired URL. This tiny document is added to IPFS  and a link to the document is returned.  just like code below: 

`echo '<!DOCTYPE html>'"<script>document.location.replace('https://www.example.com/');</script>" | ipfs add` 

more discussion at https://news.ycombinator.com/item?id=18750651

**Comment by hacdias** [comment]
What do you think @koalalorenzo?

**Comment by koalalorenzo** [comment]
> What do you think @koalalorenzo?

It would be nice if it was open source (or if the "short" version was actual shorter in IPFS).
In my opinion: It is not must-have-_awesome_, but with the source code public on GitHub it would be :) 

I guess implementing this is not that hard 😸

**Comment by hacdias** [comment]
@facert @koalalorenzo merged :)

**Pull request merged**
