### PR TITLE
feat: add understanding ipfs series

### PR DESCRIPTION
**Pull request by vasa-develop**
License: MIT
Signed-off-by: Vaibhav Saini <vasa@towardsblockchain.com>

## What kind of change is it?

- [x] Addition
- [ ] Removal
- [ ] Edit
- [ ] Other

### Checklist

- [x] I edited the `/data` directory instead of the [README.md](https://github.com/ipfs/awesome-ipfs/blob/master/README.md).
- [ ] This PR includes only one addition/removal/edit.
- [x] I ran the `make build` command following my edits to the `/data` directory.
- [x] I have followed the [CONTRIBUTING.md guidelines](https://github.com/ipfs/awesome-ipfs/blob/master/CONTRIBUTING.md).

## Details

Provide details of your changes here.

### CODE REVIEW

**Comment by hacdias** [comment]
@vasa-develop thanks for the PR! I see you are adding a series of articles (Understanding IPFS in Depth). Is there a possibility to create a main article that points to all of the parts? It would be much better than having 6 articles with the same name here.

**Comment by vasa-develop** [comment]
@hacdias Sure, I will do that.

**Comment by vasa-develop** [comment]
@hacdias done.

**Comment by hacdias** [comment]
Published! Thanks for the contributions!

**Pull request merged**
