### PR TITLE
Adds Pubswap to apps.

### PR DESCRIPTION
**Pull request by lifeBCE**
Pubswap communicates directly with the IPFS network to deliver video content to its users.

### CODE REVIEW

**Comment by fiatjaf** [comment]
Doesn't seem to be working (or at least it works in a very confusing way).

**Comment by koalalorenzo** [comment]
It could eventually use the local `go-ipfs` or the companion instead of forcing `js-ipfs`. Not sure if it is already doing that, but the experience is very bad. I guess it is because the content is not replicated enough in the network

**Comment by lifeBCE** [comment]
It is said that more than 50% of modern content is consumed via a mobile device. Mobile devices that are or may not be connected to a home wifi network. Tethering the main functionality of the service to a local IPFS node would be a bad idea given this fact alone. Most visitors will also be just casual viewers and those that would not be willing to install an IPFS node anyway.

The upload functionality does use a local node and there is logic (that is currently disabled) that can pull the content from the HTTP gateway but this is not the intent of the service. There are specific reasons for each decision in this service. Having said all of that, the functionality is flawless for me. There is currently a delay at the beginning of playing each video due to this: https://github.com/ipfs/js-ipfs/issues/1706.

I thought it was lack of availability on the network as well but this doesn't make any sense given the websocket structure. js-ipfs does not communicate directly with the DHT yet so it relays through a websocket connection on the bootstrap nodes configured in the js-ipfs client. Basic troubleshooting led to the conclusion filed in the issue linked above. There seems to be a delay in the Readable Stream implementation in the client as the blocks stream in instantly but the stream does not advertise this for a number of seconds (sometimes upwards of 10 or more).

There is also another large requirement that any browser used must support the Media Source Extension given how the player works. Apple devices do not support this yet so that sucks but unavoidable.

Pubswap was intended to be as decentralized as possible. A service that could be supported by the users themselves. No large data centers or racks of servers required. The only thing that is still centralized is the dataset of IPFS hashes linked to the textual data displayed on the site. IPFS doesn't really offer a solution for storing/indexing descriptive data for content or providing a real time full text search capability of that data.

Providing only a platform and not storing, processing or distributing the content allows the service to be hosted for much less cost and makes it much less vulnerable to de-platforming. For this, we must (for now) give up some functionality. The jury is still out on whether people are ready for such a service. Your responses here aren't very encouraging on the affirmative.

**Comment by koalalorenzo** [comment]
Your long response makes me feel that I hurt you. Sorry that was not my intention.

What I meant to say is: What if the user has an local already running ipfs node? Why don't you hook it into `window.ipfs` from the companion when it is available? This will help. 😄

**Comment by lifeBCE** [comment]
Heh, no hurt. I like to use these opportunities to document the service as I know the documentation on the site is light. My focus is on functionality ATM but the docs will improve. I do have fallback logic to stream through a local IPFS node already and will enable it when the Media Source Extension is not available (possibly).

I have it disabled for now since this will require storing each video in numerous formats to support. The content needs to be in a specific format to stream in blocks over the websocket directly into the HTML video buffer but this format will not just play over HTTP without the corresponding manifest files. Tons of material is available on this topic if further understanding is desired.

Modifying manifest files to work with IPFS CDN is one potential option in the future but that is not in place yet. As for the browser plugin, it doesn't seem necessary and would be another prerequisite to install for the service to function properly. If/when I want to support streaming content over a local HTTP gateway, I would not need or benefit from the browser plugin.

**Comment by fiatjaf** [comment]
To me it still looks you're offended and because of that failing to see that pubswap could be a really useful service if you accepted to use some of the existing centralized infrastructure we have today (like public gateways) instead of trying to achieve the impossible. You can always remove that later.

And obviously relying on the IPFS Companion when available is something you should do, and since you didn't address that in your response to @koalalorenzo maybe you don't know what is he talking about? https://github.com/ipfs-shipyard/ipfs-companion

**Comment by lifeBCE** [comment]
I am using private gateways and still have no use for the browser plugin but thanks!

FYI, disagreeing with someone does not constitute offense. Why would I be offended that some have no clue what the service does or its purpose?

**Pull request closed without merging**
